#!/bin/bash
# Decrypt polybot secrets from age-encrypted files into tmpfs at boot.
# Runs via polybot-secrets.service before any polybot-v3 services start.
#
# Migrated 2026-04-10 from /opt/polybot/boot_decrypt_secrets.sh as part of the
# v1 deletion cleanup. The age identity key lives at /root/.config/age/polybot.key
# (not in the polybot-v3 tree — chmod 600 root-only).
#
# 2026-04-23: extended to auto-decrypt ALL wallet-*.json.age files for fleet
# entities. Each decrypted file is chmod 600 + available via symlink at
# /opt/polybot-v3/state/wallet-<slug>.json. Fleet entities reference their
# wallets via entity.entity_path + /state/wallet.json in entity-manager.

set -e

AGE_KEY=/root/.config/age/polybot.key
SECRETS_DIR=/dev/shm/polybot-secrets
V3_SECRETS_DIR=/opt/polybot-v3/secrets

# Create tmpfs secrets directory
mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"
chown polybot:polybot "$SECRETS_DIR" 2>/dev/null || chown root:root "$SECRETS_DIR"

# Decrypt api_keys.json (shared across all entities)
age -d -i "$AGE_KEY" -o "$SECRETS_DIR/api_keys.json" "$V3_SECRETS_DIR/api_keys.json.age"
chmod 600 "$SECRETS_DIR/api_keys.json"
chown polybot:polybot "$SECRETS_DIR/api_keys.json" 2>/dev/null || chown root:root "$SECRETS_DIR/api_keys.json"

# Decrypt primary wallet.json (Wallet #1 / polybot entity)
age -d -i "$AGE_KEY" -o "$SECRETS_DIR/wallet.json" "$V3_SECRETS_DIR/wallet.json.age"
chmod 600 "$SECRETS_DIR/wallet.json"
chown polybot:polybot "$SECRETS_DIR/wallet.json" 2>/dev/null || chown root:root "$SECRETS_DIR/wallet.json"

# 2026-04-23 fleet support — decrypt all wallet-<slug>.json.age files if they exist.
# These are generated by scripts/fleet-bootstrap.sh. If the fleet hasn't been
# bootstrapped yet, this loop no-ops silently.
for enc in "$V3_SECRETS_DIR"/wallet-*.json.age; do
  [ -f "$enc" ] || continue  # no matches -> glob literal, skip
  base=$(basename "$enc" .json.age)   # e.g. 'wallet-armorstack'
  out="$SECRETS_DIR/${base}.json"
  age -d -i "$AGE_KEY" -o "$out" "$enc"
  chmod 600 "$out"
  chown polybot:polybot "$out" 2>/dev/null || chown root:root "$out"
done

# Ensure the /opt/polybot-v3/state symlinks still resolve (they point here)
mkdir -p /opt/polybot-v3/state
[ -L /opt/polybot-v3/state/api_keys.json ] || ln -sf "$SECRETS_DIR/api_keys.json" /opt/polybot-v3/state/api_keys.json
[ -L /opt/polybot-v3/state/wallet.json ] || ln -sf "$SECRETS_DIR/wallet.json" /opt/polybot-v3/state/wallet.json

# 2026-04-23: symlink each fleet wallet into its entity's state directory.
# entities.yaml entity_path points at e.g. /opt/polybot-v3/paper-entities/armorstack/
# — the engine reads wallet.json from there. Create per-entity state/ dir and
# symlink the decrypted wallet-<slug>.json into it as wallet.json.
for enc in "$V3_SECRETS_DIR"/wallet-*.json.age; do
  [ -f "$enc" ] || continue
  base=$(basename "$enc" .json.age)
  slug="${base#wallet-}"   # strip leading 'wallet-'
  ENTITY_DIR="/opt/polybot-v3/paper-entities/${slug}"
  # Only create symlink if entity_path exists (entity is configured in yaml)
  if [ -d "$ENTITY_DIR" ]; then
    mkdir -p "${ENTITY_DIR}/state"
    ln -sf "$SECRETS_DIR/${base}.json" "${ENTITY_DIR}/state/wallet.json"
  fi
done

echo "Secrets decrypted to $SECRETS_DIR at $(date)"
echo "Fleet wallets decrypted: $(ls $SECRETS_DIR/wallet-*.json 2>/dev/null | wc -l)"
